//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int ID { get; set; }
        public int UsersID { get; set; }
        public int CityID { get; set; }
        public System.DateTime VisitDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
